name: GodTrident
description: $description
version: '${version}'

main: com.github.Glatinis.godTrident.GodTrident
api-version: '1.21.11'
load: POSTWORLD

authors: [ Glatinis ]

commands:
  givegodtrident:
    description: Gives the God Trident to a player.
    usage: /givegodtrident [player]

permissions:
  godtrident.give:
    description: Allows using /givegodtrident
    default: op
